### ISSUE TITLE
Request for Pretrained Model Weights

### ISSUE THREAD

**Issue by boboffg** [YuemingJin/STswinCL#5]
I want to express my appreciation for sharing your open-source project. It has been valuable for my research. While attempting to reproduce your paper's results, I've encountered challenges, particularly with the time and GPU memory required for model training.

I noticed that the model training is resource-intensive. Therefore, I'd like to kindly inquire if it's possible to provide pretrained model weights. This would significantly expedite replication of your work and make it more accessible to researchers with limited resources.

Thank you for your open-source contribution and outstanding research.

**Comment by haipeeee** [comment]
I'm encountering the same issue, and I completely agree with the request. It would be incredibly helpful to have pretrained model weights available, especially for researchers like me with resource limitations. Thank you for bringing this up!
